merge from trunk

diff --git a/winsup/cygwin/speclib b/winsup/cygwin/speclib
--- a/winsup/cygwin/speclib
+++ b/winsup/cygwin/speclib
@@ -1,82 +1,39 @@
-#!/usr/bin/perl
-use Getopt::Long;
-use File::Temp qw'tempdir';
-use File::Basename;
-use File::Spec;
-use strict;
+#!/bin/sh -x
+# speclib - Make a special version of the cygwin import library.
+#
+#   Copyright 2001, 2002 Red Hat, Inc.
+#
+# This file is part of Cygwin.
+#
+# This software is a copyrighted work licensed under the terms of the
+# Cygwin license.  Please consult the file "CYGWIN_LICENSE" for
+# details.
 
-sub dllname($;$);
+case "$1" in
+    -v) shift; v() { :; } ;;
+    *) v() { /bin/false; } ;;
+esac
+lib=$1; shift
+nm=$1; shift
+ar=$1; shift
+libdll=$1; shift
+cp /dev/null /tmp/$$.objs
+trap "/bin/rm -rf /tmp/$$.dir /tmp/$$.syms /tmp/$$.objs /tmp/$$.raw" 0 1 2 15
+$nm --extern-only --defined-only $* | sed -e '/^[ 	]*$/d' -e '/:$/d' -e 's%^.* _\(.*\)%/ __imp__\1$/p%' | grep -v ' __imp___imp__' > /tmp/$$.syms
+v || $nm -Ap --extern-only --defined-only $libdll | egrep ' I __head| I _.*_iname' |  awk -F: '{print $2}' > /tmp/$$.objs
+$nm -Ap --extern-only --defined-only $libdll | sed -n -f /tmp/$$.syms | awk -F: '{print $2}' >> /tmp/$$.objs
+sort -o /tmp/$$.objs -u /tmp/$$.objs
 
-my $static;
-my $inverse;
-my @exclude;
+[ -s /tmp/$$.objs ] || { echo "speclib: couldn't find symbols for $lib" 1>&2; exit 1; }
 
-my ($ar, $as, $nm, $objcopy);
-GetOptions('exclude=s'=>\@exclude, 'static!'=>\$static, 'v!'=>\$inverse,
-	   'ar=s'=>\$ar, 'as=s'=>\$as,'nm=s'=>\$nm, 'objcopy=s'=>\$objcopy);
-
-$_ = File::Spec->rel2abs($_) for @ARGV;
-
-my $libdll = shift;
-my $lib =  pop;
-(my $iname = basename $lib) =~ s/\.a$//o;
-$iname = '_' . $iname . '_dll_iname';
-
-open my $nm_fd, '-|', $nm, '-Apg', '--defined-only', @ARGV, $libdll or
-  die "$0: execution of $nm for object files failed - $!\n";
-
-my %match_syms = ();
-my $symfiles = ();
-my $lastfn;
-my %extract = ();
-my $exclude_regex = @exclude ? join('|', @exclude) : '\\UnLiKeLy//';
-$exclude_regex = qr/$exclude_regex/;
-my $dllname;
-while (<$nm_fd>) {
-    study;
-    if (/ I _(.*)_dll_iname/o) {
-	$dllname = $1;
-    } else {
-	my ($file, $member, $symbol) = m%^([^:]*):([^:]*(?=:))?.* T (.*)%o;
-	next if !defined($symbol) || $symbol =~ $exclude_regex;
-	if ($file ne $libdll) {
-	     $match_syms{$symbol} = 1;
-	 } elsif ($match_syms{$symbol} ? !$inverse : $inverse) {
-	     $extract{$member} = 1;
-	 }
-    }
-}
-close $nm_fd;
-   
-
-%extract or die "$0: couldn't find symbols for $lib\n";
-
-my $dir = tempdir(CLEANUP => 1);
-
-chdir $dir;
-# print join(' ', '+', $ar, 'x', sort keys %extract), "\n";
-my $res = system $ar, 'x', $libdll, sort keys %extract;
-die "$0: $ar extraction exited with non-zero status\n" if $res;
-unlink $lib;
-
-# Add a dummy .idata object for libtool so that it will think
-# this library is an import library.
-my $iname_o = 'd000000.o';
-$extract{$iname_o} = 1;
-open my $as_fd, '|-', $as, '-R', '-o', $iname_o, "-";
-print $as_fd <<EOF;
-	.section .idata\$7
-.global $iname
-$iname: .asciz "$dllname.dll"
-EOF
-close $as_fd or exit 1;
-system $objcopy, '-j', '.idata$7', $iname_o;
-
-$res = system $ar, 'crus', $lib, sort keys %extract;
-unlink keys %extract;
-die "$0: ar creation of $lib exited with non-zero status\n" if $res;
-exit 0;
-
-END {
-    chdir '/tmp';	# Allow $dir directory removal on Windows
-}
+/bin/rm -f /tmp/$$>dir
+mkdir /tmp/$$.dir
+cd /tmp/$$.dir
+if v; then
+    $ar x $libdll
+    /bin/rm -f `cat /tmp/$$.objs`
+else
+    $ar x $libdll `cat /tmp/$$.objs`
+fi
+/bin/rm -f $lib
+$ar crus $lib *.o
